# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 1200
cpus_per_task: 8
ntasks_per_node: ${trainer.devices}
gres: "gpu:2"
name: ${hydra.job.name}
constraint: "a100"
account: "xyw@a100"
additional_parameters:
  hint: nomultithread
setup:
  - module purge
  - source ${oc.env:HOME}/.bash_profile
  - module load arch/a100
  - module load pytorch-gpu/py3/2.3.0