# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 6000
cpus_per_task: 8
ntasks_per_node: 8
gres: "gpu:8"
name: ${hydra.job.name}
partition: "gpu_p2"
qos: "qos_gpu-t4"
account: "xyw@v100"
additional_parameters:
  hint: nomultithread
setup:
  - module purge
  - source ${oc.env:HOME}/.bash_profile
  - module load pytorch-gpu/py3/2.3.0
