_target_: multi_sources.structure.deterministic.MultisourceDeterministicReconstructor
patch_size: 16
values_dim: ${model.values_dim}
coords_dim: ${model.coords_dim}
n_sources_to_mask: 1
lr_scheduler_kwargs: ${lr_scheduler}
loss_max_distance_from_center: null
ignore_land_pixels_in_loss: false 
adamw_kwargs: ${optimizer}
metrics: ${metrics}

backbone: ${model.backbone}
output_resnet_blocks: ${model.output_resnet_blocks}
output_resnet_channels: ${model.output_resnet_channels}