_target_: multi_sources.structure.generative.MultisourceFlowMatchingReconstructor
patch_size: 16
values_dim: ${model.values_dim}
coords_dim: ${model.coords_dim}
n_sources_to_mask: 1
lr_scheduler_kwargs: ${lr_scheduler}
adamw_kwargs: ${optimizer}
