_target_: multi_sources.structure.flow_matching.MultisourceFlowMatchingReconstructor
patch_size: 16
values_dim: ${model.values_dim}
coords_dim: ${model.coords_dim}
n_sources_to_mask: 1
n_sampling_diffusion_steps: 25
lr_scheduler_kwargs: ${lr_scheduler}
loss_max_distance_from_center: null
adamw_kwargs: ${optimizer}
metrics: ${metrics}
