_target_: multi_sources.structure.mae_reworked.MultisourceMAE
patch_size: 16
values_dim: ${model.values_dim}
coords_dim: ${model.coords_dim}
n_sources_to_mask: 1
loss_max_distance_from_center: 1000
lr_scheduler_kwargs: ${lr_scheduler}
adamw_kwargs: ${optimizer}
