# Train dataset
train:
  _target_: multi_sources.data_processing.multi_source_dataset.MultiSourceDataset
  dataset_dir: ${paths.preprocessed_dataset}
  split: train
  included_variables_dict:
    _target_: multi_sources.data_processing.utils.read_variables_dict
    variables_dict: ${sources}
  single_channel_sources: True
  # Interval in hours between two reference times
  reference_times_interval: ???
  # Maximum number of hours between the sample synoptic time
  # and an observation included within the sample.
  dt_max: ???
  # Minimum proportion of the sources that must be available at a given (synoptic time, storm)
  # for the sample to be yielded by the dataset.
  min_available_sources_prop: ???
  enable_data_augmentation: false

# Validation dataset
val:
  _target_: multi_sources.data_processing.multi_source_dataset.MultiSourceDataset
  dataset_dir: ${paths.preprocessed_dataset}
  split: val
  included_variables_dict:
    _target_: multi_sources.data_processing.utils.read_variables_dict
    variables_dict: ${sources}
  single_channel_sources: True
  reference_times_interval: ${dataset.train.reference_times_interval}
  dt_max: ${dataset.train.dt_max}
  min_available_sources_prop: ${dataset.train.min_available_sources_prop}
