# Train dataset
train:
  _target_: multi_sources.data_processing.multi_source_dataset.MultiSourceDataset
  dataset_dir: ${paths.preprocessed_dataset}
  split: train
  included_variables_dict:
    _target_: multi_sources.data_processing.utils.read_variables_dict
    variables_dict: ${sources}
  # Maximum difference of time in hours between an observation's time
  # and the sample's reference time.
  dt_max: ???
  # Minimum number of sources that must be available in a sample
  # for it to be included in the dataset.
  min_available_sources: ???
  # Number of workers for the data loading
  num_workers: ${dataloader.num_workers}
  # By default, don't drop any sources
  randomly_drop_sources: {}
  # By default, don't select the most recent sources
  select_most_recent: false
  # Whether to mask the spatial coordinates of the sources
  mask_spatial_coords: []
  # Data augmentation to apply
  data_augmentation: ${data_augmentation}

# Validation dataset
val:
  _target_: multi_sources.data_processing.multi_source_dataset.MultiSourceDataset
  dataset_dir: ${paths.preprocessed_dataset}
  split: val
  included_variables_dict:
    _target_: multi_sources.data_processing.utils.read_variables_dict
    variables_dict: ${sources}
  dt_max: ${dataset.train.dt_max}
  min_available_sources: ${dataset.train.min_available_sources}
  num_workers: ${dataset.train.num_workers}
  randomly_drop_sources: ${dataset.train.randomly_drop_sources}
  select_most_recent: ${dataset.train.select_most_recent}
  mask_spatial_coords: ${dataset.train.mask_spatial_coords}
  data_augmentation: null

# Test dataset
test:
  _target_: multi_sources.data_processing.multi_source_dataset.MultiSourceDataset
  dataset_dir: ${paths.preprocessed_dataset}
  split: test
  included_variables_dict:
    _target_: multi_sources.data_processing.utils.read_variables_dict
    variables_dict: ${sources}
  dt_max: ${dataset.train.dt_max}
  min_available_sources: ${dataset.train.min_available_sources}
  num_workers: ${dataset.train.num_workers}
  randomly_drop_sources: ${dataset.train.randomly_drop_sources}
  select_most_recent: ${dataset.train.select_most_recent}
  mask_spatial_coords: ${dataset.train.mask_spatial_coords}
  data_augmentation: null