visual:
  _target_: multi_sources.eval.visualization.VisualEvaluationComparison
  eval_fraction: 1.0
  max_realizations_to_display: 6
  source_name_replacements: [
    ["tc_primed_pmw_", ""],
    ["_", " "]
  ]
  channel_replacements: [
    ["TB_", ""],
    ["36.5", "37.0"],
    ["36.64", "37.0"],
    ["A89.0", "89.0"],
    ["B89.0", "89.0"],
    ["89.0", "89.0"],
    ["85.5", "89.0"],
    ["91.665", "89.0"]
  ]
  disable_checks: ${disable_checks}