defaults:
  - paths/local
  - wandb/default
  - sources:
    - test
  - dataset/multi_sources
  - dataloader/local
  - lightning_module:
    - mae
  - model:
      - unet
  - trainer/local
  - lr_scheduler:
    - test
  - eval:
    - local
