defaults:
  - paths/local
  - wandb/default
  - sources:
    - test
  - dataset/selected_microwave
  - dataloader/local
  - experiment:
    - test
  - model:
      - unet
  - trainer/local
  - lr_scheduler:
    - test
