defaults:
  - paths: local
  - wandb: default
  - sources: amsr2_5freqs
  - dataset: default
  - dataloader: local
  - lightning_module: mae
  - model: general_backbone
  - trainer: 1gpu
  - lr_scheduler: cosine_warmup_150epochs
  - optimizer: default_adamw
  - _self_

seed: 42
