defaults:
  - paths: jz
  - wandb: default
  - sources: ???
  - dataset: default
  - data_augmentation: none
  - dataloader: jz
  - lightning_module: flow_matching
  - model: ???
  - trainer: ???
  - lr_scheduler: cosine_warmup_50epochs
  - optimizer: default_adamw
  - metrics: none
  - _self_

seed: 42
