defaults:
  - paths: local
  - wandb: default
  - sources: test
  - dataset: full_set
  - dataloader: local
  - lightning_module: mae
  - model: mae
  - trainer: 1xv100-32g
  - lr_scheduler: cosine_warmup_300epochs
  - _self_

seed: 42
