defaults:
  - paths: jz
  - wandb: default
  - sources: sat_interp_37GHz
  - dataset: default
  - data_augmentation: none
  - dataloader: jz
  - lightning_module: mae
  - model: vit_69M
  - trainer: 1gpu
  - lr_scheduler: cosine_warmup_50epochs
  - optimizer: default_adamw
  - _self_

seed: 42
