defaults:
  - paths: local
  - wandb: default
  - sources:
    - swath_interpolation
  - dataset: full_set
  - dataloader: local
  - lightning_module:
    - mae
  - model:
      - vit_test
  - trainer: local
  - lr_scheduler:
    - cosine_warmup_150epochs
