defaults:
  - paths/local
  - wandb/default
  - sources:
    - satellite_interpolation
  - dataset/full_set
  - dataloader/local
  - lightning_module:
    - mae
  - model:
      - vit
  - trainer/local
  - lr_scheduler:
    - cosine_warmup_100epochs
