defaults:
  - paths: jz
  - wandb: default
  - sources:
    - satellite_interpolation
  - dataset: full_set
  - dataloader: jz
  - lightning_module:
    - mae
  - model:
      - vit
  - trainer: 4xv100-32g
  - lr_scheduler:
    - cosine_warmup_150epochs
