encoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  n_blocks: ???
  metadata_dim: ${lightning_module.metadata_dim}
  values_dim: ${lightning_module.values_dim}
  layers: ???
decoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  n_blocks: ???
  metadata_dim: ${lightning_module.metadata_dim}
  values_dim: ${lightning_module.values_dim}
  layers: ???
