encoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  patch_size: ${lightning_module.patch_size}
  n_blocks: ???
  coords_dim: ${lightning_module.coords_dim}
  values_dim: ${lightning_module.values_dim}
  layers: ???
decoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  patch_size: ${lightning_module.patch_size}
  n_blocks: ???
  coords_dim: ${lightning_module.coords_dim}
  values_dim: ${lightning_module.values_dim}
  layers: ???
