encoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  patch_size: ${lightning_module.patch_size}
  n_blocks: 1
  coords_dim: ${lightning_module.coords_dim}
  pixels_dim: ${lightning_module.pixels_dim}
decoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  patch_size: ${lightning_module.patch_size}
  n_blocks: 1
  coords_dim: ${lightning_module.coords_dim}
  pixels_dim: ${lightning_module.pixels_dim}
