dropout: 0.0
values_dim: 256
coords_dim: 256
backbone:
  _target_: multi_sources.models.motif_single_embed.backbone.MultisourceGeneralBackbone
  values_dim: ${lightning_module.values_dim}
  coords_dim: ${lightning_module.coords_dim}
  sum_or_concat_coords: "sum"
  n_blocks: 8
  dropout: ${model.dropout}
  att_inner_ratio: 1.0
  cross_att_inner_ratio_v: 1.0
  mlp_inner_ratio: 2.0
  num_heads: 8
  cross_att_window_size: 4
  iwsa_window_size: 8

output_resnet_channels: null
output_resnet_blocks: null
