dropout: 0.0
values_dim: 384
coords_dim: 192
backbone:
  _target_: multi_sources.models.motif_double.backbone.MultisourceGeneralBackbone
  values_dim: ${lightning_module.values_dim}
  coords_dim: ${lightning_module.coords_dim}
  n_blocks: 12
  dropout: ${model.dropout}
  att_inner_ratio: 1.0
  mlp_inner_ratio: 2.0
  num_heads: 8
  cross_att_window_size: 4
  iwsa_window_size: 8

output_resnet_blocks: 5
output_resnet_channels: 64