dropout: 0.0
values_dim: 128
coords_dim: 64
backbone:
  _target_: multi_sources.models.backbone.MultisourceGeneralBackbone
  values_dim: ${lightning_module.values_dim}
  coords_dim: ${lightning_module.coords_dim}
  n_blocks: 6
  layers:
    cross_attention:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.MultisourcesAnchoredCrossAttention
      inner_ratio: 1
      anchor_points_spacing: 6
      num_heads: 4
      dropout: ${model.dropout}
    spatial_attention:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.SeparateWindowedValuesCoordinatesAttention
      inner_ratio: 1
      window_size: 8
      num_heads: 4
      dropout: ${model.dropout}
    ff1:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.small_layers.FeedForward
      inner_ratio: 1
      dropout: ${model.dropout}
