dropout: 0.0
values_dim: 256
coords_dim: 256
backbone:
  _target_: multi_sources.models.motif_double.backbone.MultisourceGeneralBackbone
  values_dim: ${lightning_module.values_dim}
  coords_dim: ${lightning_module.coords_dim}
  n_blocks: 8
  dropout: ${model.dropout}
  att_inner_ratio: 1
  mlp_inner_ratio: 2
  num_heads: 8
  anchor_points_spacing: 4
  window_size: 8
