dropout: 0.0
values_dim: 512
coords_dim: 512
backbone:
  _target_: multi_sources.models.backbone.MultisourceGeneralBackbone
  values_dim: ${lightning_module.values_dim}
  coords_dim: ${lightning_module.coords_dim}
  n_blocks: 8
  layers:
    cross_attention:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.MultisourcesAnchoredCrossAttention
      inner_dim: 512
      num_anchor_points: 64
      num_heads: 8
      dropout: ${model.dropout}
    spatial_attention:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.SeparateWindowedValuesCoordinatesAttention
      inner_dim: 512
      window_size: 7
      num_heads: 8
      dropout: ${model.dropout}
    ff1:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.small_layers.FeedForward
      inner_ratio: 4
      dropout: ${model.dropout}
