_target_: multi_sources.models.regridding_vit.RegriddingTransformer
patch_size: 16
c_dim: 256
inner_channels: 16
depth: 2
downsample: True
heads: 2
dim_head: 256
kernel_size: 7
output_resnet_depth: 1
output_resnet_kernel_size: 7
