encoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  patch_size: ${lightning_module.patch_size}
  coords_dim: ${lightning_module.coords_dim}
  pixels_dim: ${lightning_module.pixels_dim}
  n_blocks: 0
  layers:

decoder:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  patch_size: ${lightning_module.patch_size}
  coords_dim: ${lightning_module.coords_dim}
  pixels_dim: ${lightning_module.pixels_dim}
  n_blocks: 0
  layers:

output_conv:
  _target_: multi_sources.models.conv.ResNet
  channels: 1
  inner_channels: 8
  n_blocks: 4
  kernel_size: 3
