dropout: 0.0
values_dim: 512
coords_dim: 512
backbone:
  _target_: multi_sources.models.general_backbone.MultisourceGeneralBackbone
  values_dim: ${lightning_module.coords_dim}
  coords_dim: ${lightning_module.values_dim}
  n_blocks: 14
  layers:
    cross_attention:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.MultisourcesAnchoredCrossAttention
      inner_dim: 512
      num_anchor_points: 128
      num_heads: 8
      dropout: ${model.dropout}
    spatial_attention:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.SeparateWindowedValuesCoordinatesAttention
      inner_dim: 512
      window_size: 7
      shifted: false
      num_heads: 8
      dropout: ${model.dropout}
    spatial_attention_shifted:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.factorized_attention.SeparateWindowedValuesCoordinatesAttention
      inner_dim: 512
      window_size: 7
      shifted: true
      num_heads: 8
      dropout: ${model.dropout}
    ff1:
      layer_class:
        _target_: hydra.utils.get_class
        path: multi_sources.models.small_layers.SwiGLU
      inner_dim: 512
      dropout: ${model.dropout}
