# Data augmentation config file.
# This cfg leads to the instantiation of a MultisourceDataAugmentation object.
_target_: multi_sources.data_processing.data_augmentation.MultisourceDataAugmentation
augmentation_functions:
  # List of data augmentation classes. Such classes must be callable with the signature
  # `__call__(self, data: Dict[str, Any]) -> Dict[str, Any]`.
  # the function multi_sources.data_processing.data_augmentation.wrap_tv_image_transform
  # can be used to wrap torchvision v2 transforms to the expected signature.
  # For the fill values, use ${nan:}.
  - _target_: multi_sources.data_processing.data_augmentation.Add_noise_to_timedelta
    relative_noise_std: 0.1
  - _target_: multi_sources.data_processing.data_augmentation.wrap_tv_image_transform
    transform:
      _target_: torchvision.transforms.v2.RandomHorizontalFlip
      p: 0.5
  - _target_: multi_sources.data_processing.data_augmentation.wrap_tv_image_transform
    transform:
      _target_: torchvision.transforms.v2.RandomRotation
      degrees: 90
      fill: ${nan:}