max_epochs: ${lr_scheduler.first_cycle_steps}
accelerator: gpu
devices: 2
precision: 16-mixed
gradient_clip_val: 1.0
strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  find_unused_parameters: true  # as we have a variable number of sources
  gradient_as_bucket_view: true  # to reduce peak memory usage